#if !canImport(ObjectiveC)
import XCTest

extension ChainTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ChainTests = [
        ("test_forwarding_chain_forwards_action", test_forwarding_chain_forwards_action)
    ]
}

extension DictionaryExtensionsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DictionaryExtensionsTests = [
        ("test_get_or_put", test_get_or_put),
        ("test_unrapping_subscript", test_unrapping_subscript)
    ]
}

extension DispatcherTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DispatcherTests = [
        ("test_add_remove_middleware", test_add_remove_middleware),
        ("test_add_remove_service", test_add_remove_service),
        ("test_subscription_count", test_subscription_count)
    ]
}

extension ReducerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ReducerTests = [
        ("test_dispatcher_triggers_action_in_reducer_group_reducer", test_dispatcher_triggers_action_in_reducer_group_reducer),
        ("test_no_subscribe_to_store_produces_no_changes", test_no_subscribe_to_store_produces_no_changes),
        ("test_reset_state", test_reset_state),
        ("test_subscribe_to_store_receive_actions", test_subscribe_to_store_receive_actions)
    ]
}

extension TaskTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TaskTests = [
        ("test_check_states_for_failure_task", test_check_states_for_failure_task),
        ("test_check_states_for_running_task", test_check_states_for_running_task),
        ("test_check_states_for_success_task", test_check_states_for_success_task),
        ("test_data_and_progress", test_data_and_progress),
        ("test_expiration_of_task_created_with_past_date", test_expiration_of_task_created_with_past_date),
        ("test_success_task_with_expiration_setted", test_success_task_with_expiration_setted),
        ("test_success_task_with_expiration_setted_to_immediately", test_success_task_with_expiration_setted_to_immediately)
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ChainTests.__allTests__ChainTests),
        testCase(DictionaryExtensionsTests.__allTests__DictionaryExtensionsTests),
        testCase(DispatcherTests.__allTests__DispatcherTests),
        testCase(ReducerTests.__allTests__ReducerTests),
        testCase(TaskTests.__allTests__TaskTests)
    ]
}
#endif
