#if !canImport(ObjectiveC)
import XCTest

extension MiniSwiftTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MiniSwiftTests = [
        ("test_dispatcher_triggers_action_in_reducer_group_reducer", test_dispatcher_triggers_action_in_reducer_group_reducer),
        ("test_no_subscribe_to_store_produces_no_changes", test_no_subscribe_to_store_produces_no_changes),
        ("test_reset_state", test_reset_state),
        ("test_subscribe_to_store_receive_actions", test_subscribe_to_store_receive_actions),
    ]
}

extension TaskTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TaskTests = [
        ("test_check_states_for_failure_task", test_check_states_for_failure_task),
        ("test_check_states_for_running_task", test_check_states_for_running_task),
        ("test_check_states_for_success_task", test_check_states_for_success_task),
        ("test_data_and_progress", test_data_and_progress),
        ("test_expiration_of_task_created_with_past_date", test_expiration_of_task_created_with_past_date),
        ("test_success_task_with_expiration_setted", test_success_task_with_expiration_setted),
        ("test_success_task_with_expiration_setted_to_immediately", test_success_task_with_expiration_setted_to_immediately),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(MiniSwiftTests.__allTests__MiniSwiftTests),
        testCase(TaskTests.__allTests__TaskTests),
    ]
}
#endif
