#if !canImport(ObjectiveC)
import XCTest

extension ChainTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ChainTests = [
        ("test_forwarding_chain_forwards_action", test_forwarding_chain_forwards_action),
    ]
}

extension CreateTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CreateTests = [
        ("test_performs_closure_action", test_performs_closure_action),
    ]
}

extension DictionaryExtensions {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DictionaryExtensions = [
        ("test_get_or_put", test_get_or_put),
        ("test_unrapping_subscript", test_unrapping_subscript),
    ]
}

extension DispatchTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DispatchTests = [
        ("test_dispatch_executes_certain_given_action", test_dispatch_executes_certain_given_action),
    ]
}

extension DispatcherTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DispatcherTests = [
        ("test_add_remove_middleware", test_add_remove_middleware),
        ("test_add_remove_service", test_add_remove_service),
        ("test_subscription_count", test_subscription_count),
    ]
}

extension FilterOneTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__FilterOneTests = [
        ("test_filter_one", test_filter_one),
    ]
}

extension MiniSwiftTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MiniSwiftTests = [
        ("test_dispatcher_triggers_action_in_reducer_group_reducer", test_dispatcher_triggers_action_in_reducer_group_reducer),
        ("test_no_subscribe_to_store_produces_no_changes", test_no_subscribe_to_store_produces_no_changes),
        ("test_reset_state", test_reset_state),
        ("test_subscribe_to_store_receive_actions", test_subscribe_to_store_receive_actions),
    ]
}

extension TaskTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TaskTests = [
        ("test_check_states_for_failure_task", test_check_states_for_failure_task),
        ("test_check_states_for_running_task", test_check_states_for_running_task),
        ("test_check_states_for_success_task", test_check_states_for_success_task),
        ("test_data_and_progress", test_data_and_progress),
        ("test_expiration_of_task_created_with_past_date", test_expiration_of_task_created_with_past_date),
        ("test_success_task_with_expiration_setted", test_success_task_with_expiration_setted),
        ("test_success_task_with_expiration_setted_to_immediately", test_success_task_with_expiration_setted_to_immediately),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ChainTests.__allTests__ChainTests),
        testCase(CreateTests.__allTests__CreateTests),
        testCase(DictionaryExtensions.__allTests__DictionaryExtensions),
        testCase(DispatchTests.__allTests__DispatchTests),
        testCase(DispatcherTests.__allTests__DispatcherTests),
        testCase(FilterOneTests.__allTests__FilterOneTests),
        testCase(MiniSwiftTests.__allTests__MiniSwiftTests),
        testCase(TaskTests.__allTests__TaskTests),
    ]
}
#endif
