default_platform(:ios)

platform :ios do
  desc "Pass all test for main target"
  lane :pass_tests do
    Dir.chdir('..') do
        #sh "xcodebuild -scheme Mini-Package -enableCodeCoverage YES clean test -destination 'platform=iOS Simulator,name=iPhone 8,OS=12.1' | xcpretty -f `xcpretty-travis-formatter`"
        #sh "curl -s https://codecov.io/bash | bash -s -- -F ios -J 'Mini'"

        sh "xcodebuild -scheme Mini-Package -enableCodeCoverage YES clean test -destination 'platform=OS X,arch=x86_64' | xcpretty -f `xcpretty-travis-formatter`"
        sh "curl -s https://codecov.io/bash | bash -s -- -F mac -J 'Mini'"

        sh "xcodebuild -scheme Mini-Package -enableCodeCoverage YES clean test -destination 'platform=tvOS Simulator,name=Apple TV,OS=12.1' | xcpretty -f `xcpretty-travis-formatter`"
        sh "curl -s https://codecov.io/bash | bash -s -- -F tv -J 'Mini'"
    end
  end

  lane :tests do
    scan(
      build_for_testing: true,
      clean: true,
      scheme: 'Mini-Package',
      code_coverage: true,
      prelaunch_simulator: true,
      device: 'iPhone 8'
    )
    sh "curl -s https://codecov.io/bash | bash -s -- -F ios -J 'Mini'"
  end
end
