default_platform(:ios)

platform :ios do
  desc "Pass all test for main target"
  lane :pass_tests do
  	test_scheme(scheme: "Mini-macOS", configuration: "Debug", name: "mac")
  	sh "curl -s https://codecov.io/bash | bash -s -- -F mac -J 'Mini'"

  	test_scheme(scheme: "Mini-tvOS", configuration: "Debug", name: "tv")
  	sh "curl -s https://codecov.io/bash | bash -s -- -F tv -J 'Mini'"

  	test_scheme(scheme: "Mini-iOS", configuration: "Debug", name: "iOS")
  	sh "curl -s https://codecov.io/bash | bash -s -- -F ios -J 'Mini'"
  end
end
